/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flo_util_HTKFunc */

#ifndef _Included_com_flo_util_HTKFunc
#define _Included_com_flo_util_HTKFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flo_util_HTKFunc
 * Method:    HCopy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_flo_util_HTKFunc_HCopy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_flo_util_HTKFunc
 * Method:    HInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_flo_util_HTKFunc_HInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_flo_util_HTKFunc
 * Method:    HRest
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_flo_util_HTKFunc_HRest
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_flo_util_HTKFunc
 * Method:    HVite
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_flo_util_HTKFunc_HVite
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
